//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadSpace2SaveEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TranslateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadSpace2SaveEditor.TranslateResources", typeof(TranslateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Energy.
        /// </summary>
        public static string Ammo_ContactEnergy {
            get {
                return ResourceManager.GetString("Ammo_ContactEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detonator Mines.
        /// </summary>
        public static string Ammo_DetonatorMines {
            get {
                return ResourceManager.GetString("Ammo_DetonatorMines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Fuel.
        /// </summary>
        public static string Ammo_FlameFuel {
            get {
                return ResourceManager.GetString("Ammo_FlameFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Energy.
        /// </summary>
        public static string Ammo_ForceEnergy {
            get {
                return ResourceManager.GetString("Ammo_ForceEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javelin Spears.
        /// </summary>
        public static string Ammo_JavelinSpears {
            get {
                return ResourceManager.GetString("Ammo_JavelinSpears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Racks.
        /// </summary>
        public static string Ammo_LineRacks {
            get {
                return ResourceManager.GetString("Ammo_LineRacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma Energy.
        /// </summary>
        public static string Ammo_PlasmaEnergy {
            get {
                return ResourceManager.GetString("Ammo_PlasmaEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma Energy 2.
        /// </summary>
        public static string Ammo_PlasmaEnergy2 {
            get {
                return ResourceManager.GetString("Ammo_PlasmaEnergy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rounds.
        /// </summary>
        public static string Ammo_PulseRounds {
            get {
                return ResourceManager.GetString("Ammo_PulseRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper Blades.
        /// </summary>
        public static string Ammo_RipperBlades {
            get {
                return ResourceManager.GetString("Ammo_RipperBlades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivet Bolts.
        /// </summary>
        public static string Ammo_RivetBolts {
            get {
                return ResourceManager.GetString("Ammo_RivetBolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker Shells.
        /// </summary>
        public static string Ammo_SeekerShells {
            get {
                return ResourceManager.GetString("Ammo_SeekerShells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Med Pack.
        /// </summary>
        public static string Consumable_LargeMedPack {
            get {
                return ResourceManager.GetString("Consumable_LargeMedPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Med Pack.
        /// </summary>
        public static string Consumable_MediumMedPack {
            get {
                return ResourceManager.GetString("Consumable_MediumMedPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Node.
        /// </summary>
        public static string Consumable_PowerNode {
            get {
                return ResourceManager.GetString("Consumable_PowerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Med Pack.
        /// </summary>
        public static string Consumable_SmallMedPack {
            get {
                return ResourceManager.GetString("Consumable_SmallMedPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stasis Pack.
        /// </summary>
        public static string Consumable_StasisPack {
            get {
                return ResourceManager.GetString("Consumable_StasisPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        public static string Difficulty_Easy {
            get {
                return ResourceManager.GetString("Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivalist.
        /// </summary>
        public static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Core.
        /// </summary>
        public static string Difficulty_Impossible {
            get {
                return ResourceManager.GetString("Difficulty_Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Difficulty_Normal {
            get {
                return ResourceManager.GetString("Difficulty_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zealot.
        /// </summary>
        public static string Difficulty_VeryHard {
            get {
                return ResourceManager.GetString("Difficulty_VeryHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Semiconductor.
        /// </summary>
        public static string Misc_BronzeSemiconductor {
            get {
                return ResourceManager.GetString("Misc_BronzeSemiconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Semiconductor.
        /// </summary>
        public static string Misc_DiamondSemiconductor {
            get {
                return ResourceManager.GetString("Misc_DiamondSemiconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Semiconductor.
        /// </summary>
        public static string Misc_GoldSemiconductor {
            get {
                return ResourceManager.GetString("Misc_GoldSemiconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Semiconductor 2.
        /// </summary>
        public static string Misc_GoldSemiconductor2 {
            get {
                return ResourceManager.GetString("Misc_GoldSemiconductor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peng.
        /// </summary>
        public static string Misc_Peng {
            get {
                return ResourceManager.GetString("Misc_Peng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby Semiconductor.
        /// </summary>
        public static string Misc_RubySemiconductor {
            get {
                return ResourceManager.GetString("Misc_RubySemiconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Suit Schematic.
        /// </summary>
        public static string Schematic_AdvancedSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_AdvancedSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Beam Schematic.
        /// </summary>
        public static string Schematic_ContactBeamSchematic {
            get {
                return ResourceManager.GetString("Schematic_ContactBeamSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Energy Schematic.
        /// </summary>
        public static string Schematic_ContactEnergySchematic {
            get {
                return ResourceManager.GetString("Schematic_ContactEnergySchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detonator Mines Schematic.
        /// </summary>
        public static string Schematic_DetonatorMineSchematic {
            get {
                return ResourceManager.GetString("Schematic_DetonatorMineSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detonator Schematic.
        /// </summary>
        public static string Schematic_DetonatorSchematic {
            get {
                return ResourceManager.GetString("Schematic_DetonatorSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Advanced Suit Schematic.
        /// </summary>
        public static string Schematic_EliteAdvancedSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_EliteAdvancedSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Engineering Suit Schematic.
        /// </summary>
        public static string Schematic_EliteEngineeringSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_EliteEngineeringSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Security Suit Schematic.
        /// </summary>
        public static string Schematic_EliteSecuritySuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_EliteSecuritySuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Vintage .
        /// </summary>
        public static string Schematic_EliteVintageSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_EliteVintageSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Fuel Schematic.
        /// </summary>
        public static string Schematic_FlameFuelSchematic {
            get {
                return ResourceManager.GetString("Schematic_FlameFuelSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamethrower Schematic.
        /// </summary>
        public static string Schematic_FlamethrowerSchematic {
            get {
                return ResourceManager.GetString("Schematic_FlamethrowerSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Energy Schematic.
        /// </summary>
        public static string Schematic_ForceEnergySchematic {
            get {
                return ResourceManager.GetString("Schematic_ForceEnergySchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Gun Schematic.
        /// </summary>
        public static string Schematic_ForceGunSchematic {
            get {
                return ResourceManager.GetString("Schematic_ForceGunSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker Contact Beam Schematic.
        /// </summary>
        public static string Schematic_HackerContactBeamSchematic {
            get {
                return ResourceManager.GetString("Schematic_HackerContactBeamSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker Schematic.
        /// </summary>
        public static string Schematic_HackerSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_HackerSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javelin Spears Schematic.
        /// </summary>
        public static string Schematic_JavelinSpearSchematic {
            get {
                return ResourceManager.GetString("Schematic_JavelinSpearSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Med Pack Schematic.
        /// </summary>
        public static string Schematic_LargeMedPackSchematic {
            get {
                return ResourceManager.GetString("Schematic_LargeMedPackSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Ammo Schematic.
        /// </summary>
        public static string Schematic_LineAmmoSchematic {
            get {
                return ResourceManager.GetString("Schematic_LineAmmoSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Med Pack Schematic.
        /// </summary>
        public static string Schematic_MediumMedPackSchematic {
            get {
                return ResourceManager.GetString("Schematic_MediumMedPackSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Node Schematic.
        /// </summary>
        public static string Schematic_PowerNodeSchematic {
            get {
                return ResourceManager.GetString("Schematic_PowerNodeSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rifle Schematic.
        /// </summary>
        public static string Schematic_PulseRifleSchematic {
            get {
                return ResourceManager.GetString("Schematic_PulseRifleSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rounds Schematic.
        /// </summary>
        public static string Schematic_PulseRoundsSchematic {
            get {
                return ResourceManager.GetString("Schematic_PulseRoundsSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper Energy Schematic.
        /// </summary>
        public static string Schematic_RipperEnergySchematic {
            get {
                return ResourceManager.GetString("Schematic_RipperEnergySchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper Schematic.
        /// </summary>
        public static string Schematic_RipperSchematic {
            get {
                return ResourceManager.GetString("Schematic_RipperSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Suit Schematic.
        /// </summary>
        public static string Schematic_SecuritySuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_SecuritySuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker Rifle Schematic.
        /// </summary>
        public static string Schematic_SeekerRifleSchematic {
            get {
                return ResourceManager.GetString("Schematic_SeekerRifleSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker Shells Schematic.
        /// </summary>
        public static string Schematic_SeekerShellsSchematic {
            get {
                return ResourceManager.GetString("Schematic_SeekerShellsSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stasis Pack Schematic.
        /// </summary>
        public static string Schematic_StasisPackSchematic {
            get {
                return ResourceManager.GetString("Schematic_StasisPackSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vintage Suit Schematic.
        /// </summary>
        public static string Schematic_VintageSuitSchematic {
            get {
                return ResourceManager.GetString("Schematic_VintageSuitSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Suit.
        /// </summary>
        public static string Suit_AdvancedSuit {
            get {
                return ResourceManager.GetString("Suit_AdvancedSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility Advanced Suit.
        /// </summary>
        public static string Suit_AgilityAdvancedSuit {
            get {
                return ResourceManager.GetString("Suit_AgilityAdvancedSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctic Security Suit.
        /// </summary>
        public static string Suit_ArcticSecuritySuit {
            get {
                return ResourceManager.GetString("Suit_ArcticSecuritySuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Vintage Suit.
        /// </summary>
        public static string Suit_BloodyVintageSuit {
            get {
                return ResourceManager.GetString("Suit_BloodyVintageSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthgov Security Suit.
        /// </summary>
        public static string Suit_EarthgovSecuritySuit {
            get {
                return ResourceManager.GetString("Suit_EarthgovSecuritySuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Advanced Suit.
        /// </summary>
        public static string Suit_EliteAdvancedSuit {
            get {
                return ResourceManager.GetString("Suit_EliteAdvancedSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Engineering Suit.
        /// </summary>
        public static string Suit_EliteEngineeringSuit {
            get {
                return ResourceManager.GetString("Suit_EliteEngineeringSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Security Suit.
        /// </summary>
        public static string Suit_EliteSecuritySuit {
            get {
                return ResourceManager.GetString("Suit_EliteSecuritySuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Vintage Suit.
        /// </summary>
        public static string Suit_EliteVintageSuit {
            get {
                return ResourceManager.GetString("Suit_EliteVintageSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Suit.
        /// </summary>
        public static string Suit_EngineeringSuit {
            get {
                return ResourceManager.GetString("Suit_EngineeringSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged Engineering Suit.
        /// </summary>
        public static string Suit_ForgedEngineeringSuit {
            get {
                return ResourceManager.GetString("Suit_ForgedEngineeringSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker Suit.
        /// </summary>
        public static string Suit_HackerSuit {
            get {
                return ResourceManager.GetString("Suit_HackerSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Suit.
        /// </summary>
        public static string Suit_HazardSuit {
            get {
                return ResourceManager.GetString("Suit_HazardSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Vintage Suit.
        /// </summary>
        public static string Suit_HeavyDutyVintageSuit {
            get {
                return ResourceManager.GetString("Suit_HeavyDutyVintageSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partol Suit.
        /// </summary>
        public static string Suit_PartolSuit {
            get {
                return ResourceManager.GetString("Suit_PartolSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Suit.
        /// </summary>
        public static string Suit_PatientSuit {
            get {
                return ResourceManager.GetString("Suit_PatientSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riot Security Suit.
        /// </summary>
        public static string Suit_RiotSecuritySuit {
            get {
                return ResourceManager.GetString("Suit_RiotSecuritySuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Suit.
        /// </summary>
        public static string Suit_SecuritySuit {
            get {
                return ResourceManager.GetString("Suit_SecuritySuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shockpoint Suit.
        /// </summary>
        public static string Suit_ShockpointSuit {
            get {
                return ResourceManager.GetString("Suit_ShockpointSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier Suit.
        /// </summary>
        public static string Suit_SoldierSuit {
            get {
                return ResourceManager.GetString("Suit_SoldierSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triage Suit.
        /// </summary>
        public static string Suit_TriageSuit {
            get {
                return ResourceManager.GetString("Suit_TriageSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vintage Suit.
        /// </summary>
        public static string Suit_VintageSuit {
            get {
                return ResourceManager.GetString("Suit_VintageSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zealot Suit.
        /// </summary>
        public static string Suit_ZealotSuit {
            get {
                return ResourceManager.GetString("Suit_ZealotSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility Plasma Cutter.
        /// </summary>
        public static string Weapon_AgilityPlasmaCutter {
            get {
                return ResourceManager.GetString("Weapon_AgilityPlasmaCutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility Pulse Rifle.
        /// </summary>
        public static string Weapon_AgilityPulseRifle {
            get {
                return ResourceManager.GetString("Weapon_AgilityPulseRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility Rivet Gun.
        /// </summary>
        public static string Weapon_AgilityRivetGun {
            get {
                return ResourceManager.GetString("Weapon_AgilityRivetGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Flamethrower.
        /// </summary>
        public static string Weapon_BloodyFlamethrower {
            get {
                return ResourceManager.GetString("Weapon_BloodyFlamethrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Force Gun.
        /// </summary>
        public static string Weapon_BloodyForceGun {
            get {
                return ResourceManager.GetString("Weapon_BloodyForceGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Javelin Gun.
        /// </summary>
        public static string Weapon_BloodyJavelinGun {
            get {
                return ResourceManager.GetString("Weapon_BloodyJavelinGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Beam.
        /// </summary>
        public static string Weapon_ContactBeam {
            get {
                return ResourceManager.GetString("Weapon_ContactBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detonator.
        /// </summary>
        public static string Weapon_Detonator {
            get {
                return ResourceManager.GetString("Weapon_Detonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthgov Detonator.
        /// </summary>
        public static string Weapon_EarthgovDetonator {
            get {
                return ResourceManager.GetString("Weapon_EarthgovDetonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthgov Pulse Rifle.
        /// </summary>
        public static string Weapon_EarthgovPulseRifle {
            get {
                return ResourceManager.GetString("Weapon_EarthgovPulseRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthgov Seeker Rifle.
        /// </summary>
        public static string Weapon_EarthgovSeekerRifle {
            get {
                return ResourceManager.GetString("Weapon_EarthgovSeekerRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamethrower.
        /// </summary>
        public static string Weapon_Flamethrower {
            get {
                return ResourceManager.GetString("Weapon_Flamethrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashlight.
        /// </summary>
        public static string Weapon_Flashlight {
            get {
                return ResourceManager.GetString("Weapon_Flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Gun.
        /// </summary>
        public static string Weapon_ForceGun {
            get {
                return ResourceManager.GetString("Weapon_ForceGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged Line Gun.
        /// </summary>
        public static string Weapon_ForgedLineGun {
            get {
                return ResourceManager.GetString("Weapon_ForgedLineGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged Plasma Cutter.
        /// </summary>
        public static string Weapon_ForgedPlasmaCutter {
            get {
                return ResourceManager.GetString("Weapon_ForgedPlasmaCutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged Ripper.
        /// </summary>
        public static string Weapon_ForgedRipper {
            get {
                return ResourceManager.GetString("Weapon_ForgedRipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker Contact Beam.
        /// </summary>
        public static string Weapon_HackerContactBeam {
            get {
                return ResourceManager.GetString("Weapon_HackerContactBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Cannon.
        /// </summary>
        public static string Weapon_HandCannon {
            get {
                return ResourceManager.GetString("Weapon_HandCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Line Gun.
        /// </summary>
        public static string Weapon_HazardLineGun {
            get {
                return ResourceManager.GetString("Weapon_HazardLineGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Contact Beam.
        /// </summary>
        public static string Weapon_HeavyDutyContactBeam {
            get {
                return ResourceManager.GetString("Weapon_HeavyDutyContactBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Detonator.
        /// </summary>
        public static string Weapon_HeavyDutyDetonator {
            get {
                return ResourceManager.GetString("Weapon_HeavyDutyDetonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Duty Line Gun.
        /// </summary>
        public static string Weapon_HeavyDutyLineGun {
            get {
                return ResourceManager.GetString("Weapon_HeavyDutyLineGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javelin.
        /// </summary>
        public static string Weapon_Javelin {
            get {
                return ResourceManager.GetString("Weapon_Javelin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Gun.
        /// </summary>
        public static string Weapon_LineGun {
            get {
                return ResourceManager.GetString("Weapon_LineGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Seeker Rifle.
        /// </summary>
        public static string Weapon_PatrolSeekerRifle {
            get {
                return ResourceManager.GetString("Weapon_PatrolSeekerRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma Cutter.
        /// </summary>
        public static string Weapon_PlasmaCutter {
            get {
                return ResourceManager.GetString("Weapon_PlasmaCutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rifle.
        /// </summary>
        public static string Weapon_PulseRifle {
            get {
                return ResourceManager.GetString("Weapon_PulseRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refubrished Plasma Cutter.
        /// </summary>
        public static string Weapon_RefubrishedPlasmaCutter {
            get {
                return ResourceManager.GetString("Weapon_RefubrishedPlasmaCutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper.
        /// </summary>
        public static string Weapon_Ripper {
            get {
                return ResourceManager.GetString("Weapon_Ripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivet Gun.
        /// </summary>
        public static string Weapon_RivetGun {
            get {
                return ResourceManager.GetString("Weapon_RivetGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker Rifle.
        /// </summary>
        public static string Weapon_SeekerRifle {
            get {
                return ResourceManager.GetString("Weapon_SeekerRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shockpoint Ripper.
        /// </summary>
        public static string Weapon_ShockpointRipper {
            get {
                return ResourceManager.GetString("Weapon_ShockpointRipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triage Javelin Gun.
        /// </summary>
        public static string Weapon_TriageJavelinGun {
            get {
                return ResourceManager.GetString("Weapon_TriageJavelinGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zealot Force Gun.
        /// </summary>
        public static string Weapon_ZealotForceGun {
            get {
                return ResourceManager.GetString("Weapon_ZealotForceGun", resourceCulture);
            }
        }
    }
}
